[project]
name = "dh5io"
version = "0.3.0"
description = "Python tools for DAQ-HDF5 (dh5) file format used at Brain Research Institute of University of Bremen"
authors = [
    { name = "Joscha Schmiedt", email = "schmiedt@brain.uni-bremen.de" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy", "h5py"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "data format",
    "electrophysiology",
    "hdf5",
    "daq",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
line-length = 96

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[project.scripts]
dh5tree = "dh5cli.dh5tree:main"
dh5merge = "dh5cli.dh5merge:main"
dh5browser = "dh5cli.dh5browser:main"

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=9.0.2",
    "mypy>=1.15.0",
    "ruff>=0.11.2",
    "dh5io[all]",
]
docs = [
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=2.0.0",
    "myst-parser>=2.0.0",
    "sphinx-autodoc-typehints>=1.25.0",
    "linkify-it-py>=2.0.0",
]
dhzio = ["zarr>=3.0.6"]
all = ["dh5io[test]", "dh5io[neo]", "dh5io[dhzio]", "dh5io[browser]", "dh5io[mne]"]
neo = ["neo"]
mne = ["mne"]
browser = ["ephyviewer", "PySide6", "dh5io[neo]"]
test = ["pytest", "pytest-cov", "dh5io[neo]", "dh5io[dhzio]", "dh5io[mne]"]
